# Generated by Django 4.2.13 on 2024-05-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("venue", models.TextField(default="TBA")),
                ("city", models.CharField(default="TBA", max_length=255)),
                ("venue_map_link", models.URLField(blank=True)),
                ("date_time", models.DateTimeField()),
            ],
        ),
    ]
