FROM node:20-alpine as BUILD_IMAGE
WORKDIR /app/frontend
COPY package.json ./
RUN npm install --frozen-lockfile
COPY . .
RUN npm run build
RUN npm prune --production
FROM node:22-alpine
WORKDIR /app
COPY --from=BUILD_IMAGE /app/frontend/package.json ./package.json
COPY --from=BUILD_IMAGE /app/frontend/node_modules ./node_modules
COPY --from=BUILD_IMAGE /app/frontend/.next ./.next
COPY --from=BUILD_IMAGE /app/frontend/public ./public
EXPOSE 3000
CMD ["npm", "start"]