#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py collectstatic --noinput
python manage.py migrate
exec /usr/local/bin/gunicorn djangoindia.wsgi --bind 0.0.0.0:8000 --chdir=/app