# Generated by Django 4.2.5 on 2025-01-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='test_email_recipients',
            field=models.TextField(blank=True, help_text='Enter comma-separated email addresses for the test email.'),
        ),
    ]
