# Generated by Django 4.2.5 on 2025-03-31 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_eventregistration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTaskLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('args', models.JSONField(blank=True, default=dict, help_text='default arguments present in task', null=True)),
                ('kwargs', models.JSONField(blank=True, default=dict, help_text='Additional arguments', null=True)),
                ('status', models.CharField(choices=[('successfully', 'Successfull'), ('FAILURE', 'Failure')], max_length=32)),
                ('log', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
