# Generated by Django 4.2.5 on 2025-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_remove_user_organization_user_about_user_bio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventregistration",
            options={
                "verbose_name": "Event registration (Deprecated)",
                "verbose_name_plural": "Event registrations (Deprecated)",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="cancellation_count_after_housefull",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="registrations_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventuserregistration",
            name="rsvp_notes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mastodon",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="eventuserregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("rsvped", "Rsvped"),
                    ("waitlisted", "Waitlisted"),
                    ("cancelled", "Cancelled"),
                    ("attended", "Attended"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("not_to_specify", "not_to_specify"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
