# Generated by Django 4.2.5 on 2025-01-10 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_user_avatar_alter_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventuserregistration",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Event User Registration",
                "verbose_name_plural": "Event User Registrations",
            },
        ),
        migrations.AddField(
            model_name="eventuserregistration",
            name="rsvp_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="eventuserregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_registrations",
                to="db.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventuserregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("waitlisted", "Waitlisted"),
                    ("cancelled", "Cancelled"),
                    ("attended", "Attended"),
                ],
                default="registered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventuserregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventuserregistration",
            unique_together={("user", "event")},
        ),
    ]
