# Generated by Django 4.2.5 on 2025-03-01 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_alter_eventregistration_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCommunication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("err_msg", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Event Communication",
                "verbose_name_plural": "Event Communications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="eventuserregistration",
            options={
                "verbose_name": "Event registration",
                "verbose_name_plural": "Event registrations",
            },
        ),
        migrations.AddConstraint(
            model_name="eventuserregistration",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="unique_user_event_registration"
            ),
        ),
        migrations.AddField(
            model_name="eventcommunication",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_communications",
                to="db.event",
            ),
        ),
        migrations.AddField(
            model_name="eventcommunication",
            name="recipient",
            field=models.ManyToManyField(
                related_name="event_communications", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
