# Generated by Django 4.2.5 on 2024-08-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(),
        ),
    ]
