# Generated by Django 4.2.5 on 2025-02-23 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_eventcommunication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcommunication',
            name='recipient',
        ),
        migrations.AddField(
            model_name='eventcommunication',
            name='recipient',
            field=models.ManyToManyField(related_name='email_communications', to=settings.AUTH_USER_MODEL),
        ),
    ]
