# Generated by Django 4.2.5 on 2024-08-18 20:29

import datetime
from django.db import migrations, models
import django.utils.timezone


def add_created_at_value(apps, schema_editor):
    contactus = apps.get_model('db', 'contactus')
    event = apps.get_model('db', 'event')
    eventregistration = apps.get_model('db', 'eventregistration')
    newslettersubscription = apps.get_model('db', 'newslettersubscription')

    contactus.objects.update(created_at=django.utils.timezone.now())
    event.objects.update(created_at=django.utils.timezone.now())
    eventregistration.objects.update(created_at=django.utils.timezone.now())
    newslettersubscription.objects.update(created_at=django.utils.timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0004_alter_contactus_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 18, 20, 29, 29, 639429,
                                                                                    tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(add_created_at_value),
    ]
