# Generated by Django 4.2.5 on 2025-02-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_alter_eventuserregistration_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventregistration",
            options={
                "verbose_name": "Event registration (Deprecated)",
                "verbose_name_plural": "Event registrations (Deprecated)",
            },
        ),
    ]
