<<<<<<< HEAD
# Generated by Django 4.2.5 on 2024-08-21 16:23
=======
# Generated by Django 4.2.5 on 2024-08-20 18:27
>>>>>>> 5d330a6 (migrations and minor changes)

from django.db import migrations, models
import djangoindia.db.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_contactus_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_time',
            new_name='event_end_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('In-person', 'In-person'), ('Online', 'Online')], default='In-person', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(default=djangoindia.db.models.event.default_start_date),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_end_date',
            field=models.DateTimeField(default=djangoindia.db.models.event.default_registration_end_date),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, default='TBA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.TextField(blank=True, default='TBA', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_map_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
