# Generated by Django 5.0.7 on 2024-08-18 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_contactus_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('update_type', models.CharField(choices=[('DJANGO_UPDATE', 'Django Update'), ('EVENT_UPDATE', 'Event Update'), ('NEWSLETTER', 'Newsletter'), ('COMMUNITY_UPDATE', 'Community Update')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('failed_to_send', models.ManyToManyField(blank=True, related_name='failed_updates', to='db.newslettersubscription')),
                ('send_to', models.ManyToManyField(blank=True, related_name='updates', to='db.newslettersubscription')),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
            },
        ),
    ]
