# Generated by Django 4.2.5 on 2024-08-19 14:53

import djangoindia.db.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_alter_contactus_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date_time",
            new_name="registration_end_date",
        ),
        migrations.AddField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_mode",
            field=models.CharField(
                choices=[("In-person", "In-person"), ("Online", "Online")],
                default="In-person",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_start_date",
            field=models.DateTimeField(
                default=djangoindia.db.models.event.default_start_date
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue_map_link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
