# Generated by Django 4.2.5 on 2025-02-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_alter_eventregistration_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cancellation_count_after_housefull",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="registrations_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mastodon",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("not_to_specify", "not_to_specify"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
