# Generated by Django 4.2.5 on 2025-02-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_alter_eventregistration_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cancellation_count_after_housefull",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="registrations_open",
            field=models.BooleanField(default=False),
        ),
    ]
