# Generated by Django 4.2.5 on 2024-08-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_date_time_event_registration_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_map_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
