# Generated by Django 4.2.5 on 2024-09-19 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangoindia.db.models.event
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0006_contactus_created_at_contactus_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('individual', 'individual'), ('organization', 'organization')], max_length=20)),
                ('logo', models.ImageField(upload_to='sponsors/logos/')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_start_date',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='occupation',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='professional_status',
            field=models.CharField(choices=[('working_professional', 'working_professional'), ('student', 'student'), ('freelancer', 'freelancer'), ('other', 'other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='Male', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='other_links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RenameModel(
            old_name='NewsletterSubscription',
            new_name='Subscriber',
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('django_update', 'Django Update'), ('event_update', 'Event Update'), ('newsletter', 'Newsletter'), ('community_update', 'Community Update')], max_length=20)),
                ('html_template', models.TextField()),
                ('mail_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='received_updates', to='db.subscriber')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('platinum', 'platinum'), ('gold', 'gold'), ('silver', 'silver'), ('individual', 'individual'), ('organization', 'organization')], max_length=20)),
                ('type', models.CharField(choices=[('community_sponsorship', 'community_sponsorship'), ('event_sponsorship', 'event_sponsorship')], max_length=30)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='db.event')),
                ('sponsor_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='db.sponsor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
