# Generated by Django 4.2.5 on 2024-08-24 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_contactus_created_at_contactus_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVolunteers',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('linkedin_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('bio', models.CharField(max_length=5000)),
                ('events', models.ManyToManyField(related_name='events', to='db.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
