# Generated by Django 4.2.5 on 2024-08-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_eventvolunteers'),
        ('db', '0007_sponsor_sponsorship'),
    ]

    operations = [
    ]
