# Generated by Django 4.2.5 on 2024-09-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_sponsor_remove_event_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='seats_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='amount_inr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online')], default='in_person', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='professional_status',
            field=models.CharField(choices=[('working_professional', 'Working Professional'), ('student', 'Student'), ('freelancer', 'Freelancer'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='tier',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('venue_sponsors', 'Venue Sponsors'), ('food_sponsors', 'Food Sponsors'), ('schwag_sponsors', 'Schwag Sponsors'), ('grant', 'Grant'), ('individual', 'Individual'), ('organization', 'Organization')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='type',
            field=models.CharField(choices=[('community_sponsorship', 'Community Sponsorship'), ('event_sponsorship', 'Event Sponsorship')], max_length=30),
        ),
    ]
