# Generated by Django 4.2.5 on 2024-09-26 14:08

from django.db import migrations, models
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Event = apps.get_model('db', 'event')
    for obj in Event.objects.all():
        if not obj.slug:
            obj.slug = slugify(obj.name)
            obj.save()

def generate_slugs_reverse(apps, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_sponsor_remove_event_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(generate_slugs, generate_slugs_reverse),
    ]
