# Generated by Django 4.2.5 on 2024-09-02 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0008_rename_newslettersubscription_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('django_update', 'Django Update'), ('event_update', 'Event Update'), ('newsletter', 'Newsletter'), ('community_update', 'Community Update')], max_length=20)),
                ('html_template', models.TextField()),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='received_updates', to='db.subscriber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
