# Generated by Django 4.2.5 on 2024-09-15 18:31

from django.db import migrations, models
import djangoindia.db.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_start_date',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='occupation',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[djangoindia.db.models.event.validate_future_date]),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, validators=[djangoindia.db.models.event.validate_future_date]),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='professional_status',
            field=models.CharField(choices=[('working_professional', 'working_professional'), ('student', 'student'), ('freelancer', 'freelancer'), ('other', 'other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[djangoindia.db.models.event.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='Male', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='other_links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
