# Generated by Django 4.2.5 on 2024-09-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
