# Generated by Django 4.2.5 on 2024-10-05 17:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPartner',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partners/logos/')),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='max_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='seats_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='include_in_attendee_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='amount_inr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online')], default='in_person', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='professional_status',
            field=models.CharField(choices=[('working_professional', 'Working Professional'), ('student', 'Student'), ('freelancer', 'Freelancer'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='tier',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('venue_sponsors', 'Venue Sponsors'), ('food_sponsors', 'Food Sponsors'), ('schwag_sponsors', 'Schwag Sponsors'), ('grant', 'Grant'), ('individual', 'Individual'), ('organization', 'Organization')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='type',
            field=models.CharField(choices=[('community_sponsorship', 'Community Sponsorship'), ('event_sponsorship', 'Event Sponsorship')], max_length=30),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteers/photos/')),
                ('name', models.CharField(max_length=255)),
                ('about', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='db.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
