# Generated by Django 4.2.5 on 2024-09-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_event_venue_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'No Disclosure')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='occupation',
            field=models.CharField(choices=[('employed', 'Employed'), ('student', 'Student'), ('freelancer', 'Freelancer')], max_length=20),
        ),
    ]
