# Generated by Django 4.2.5 on 2024-10-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0010_communitypartner_event_max_seats_event_seats_left_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="volunteer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="event",
            name="volunteers",
            field=models.ManyToManyField(to="db.volunteer"),
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="event",
        ),
    ]
