# Generated by Django 4.2.5 on 2024-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_communitypartner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypartner',
            old_name='contact_person_email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='communitypartner',
            old_name='contact_person_name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='communitypartner',
            old_name='organization_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='communitypartner',
            old_name='organization_website',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='communitypartner',
            name='contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='communitypartner',
            name='organization_email',
        ),
        migrations.AddField(
            model_name='communitypartner',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
