# Generated by Django 4.2.5 on 2024-09-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_alter_folder_unique_together'),
        ('db', '0010_event_max_seats_event_seats_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.folder'),
        ),
    ]
