# Generated by Django 5.1.2 on 2024-10-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_communitypartner_event_max_seats_event_seats_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attendee_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('host', 'Host'), ('speaker', 'Speaker'), ('volunteer', 'Volunteer')], default='guest', max_length=10),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='first_time_attendee',
            field=models.BooleanField(default=True),
        ),
    ]
