# Generated by Django 4.2.5 on 2024-09-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_remove_event_event_end_date_and_more'),
        ('db', '0011_rename_contact_person_email_communitypartner_contact_email_and_more'),
    ]

    operations = [
    ]
