# Generated by Django 4.2.5 on 2024-12-09 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0006_alter_folder_unique_together"),
        ("db", "0011_alter_volunteer_unique_together_event_volunteers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="update",
            old_name="html_template",
            new_name="email_body",
        ),
        migrations.RenameField(
            model_name="update",
            old_name="title",
            new_name="email_subject",
        ),
        migrations.AddField(
            model_name="event",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cabinet.folder",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="attendee_type",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("host", "Host"),
                    ("speaker", "Speaker"),
                    ("volunteer", "Volunteer"),
                ],
                default="guest",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="first_time_attendee",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sponsorship",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
