# Generated by Django 4.2.5 on 2024-11-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_volunteer_unique_together_event_volunteers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='attendee_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('host', 'Host'), ('speaker', 'Speaker'), ('volunteer', 'Volunteer')], default='guest', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='first_time_attendee',
            field=models.BooleanField(default=True),
        ),
    ]
