# Generated by Django 5.1.2 on 2024-12-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_rename_html_template_update_email_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
