# Generated by Django 4.2.5 on 2024-12-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0012_rename_html_template_update_email_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
