# Generated by Django 4.2.5 on 2024-12-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='test_email_recipients',
            field=models.CharField(blank=True, null=True),
        ),
    ]
