# Generated by Django 4.2.5 on 2024-12-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_event_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='html_template',
            new_name='email_body',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='title',
            new_name='email_subject',
        ),
    ]
