# Generated by Django 5.1.2 on 2024-12-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_event_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
