# Generated by Django 5.1.2 on 2024-10-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_alter_eventregistration_attendee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='attendee_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('host', 'Host'), ('speaker', 'Speaker'), ('volunteer', 'Volunteer')], max_length=20),
        ),
    ]
