# Generated by Django 5.1.2 on 2024-10-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_alter_eventregistration_attendee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='attendee_type',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
