# Generated by Django 4.2.5 on 2024-12-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0014_rename_html_template_update_email_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorship",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
