# Generated by Django 5.1.2 on 2024-10-26 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_eventregistration_attendee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypartner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
